### PR TITLE
GL Logo

### PR DESCRIPTION
**Pull request by mugman174**
Use the generic linux logo

Do a squash commit

### CODE REVIEW

**Review by cosmicle0 — APPROVED** [review]
Sure.

**Comment by mugman174** [comment]
I need to get my gpg and stuff into github

**Comment by BBaoVanC** [comment]
What is the purpose of `assets/.exists`?

Was it accidentally committed?

**Comment by mugman174** [comment]
its so that folder doesn't disappear if we ever change the logo ig

**Comment by BBaoVanC** [comment]
> its so that folder doesn't disappear if we ever change the logo ig

I don't see why it would disappear, if you mean when it's empty, then it should disappear. Can you remove the file

**Pull request merged**
